language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kocholes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kocholes/docker-react npm run test